# Uncomment this line to define a global platform for your project
platform :ios, ‘9.1’
# Uncomment this line if you're using Swift
# use_frameworks!

target 'SaveImage' do

pod 'RSKImageCropper'

end

